### ISSUE TITLE
Textual encoding for accounts

### ISSUE THREAD

**Issue by roman-kashitsyn** [dfinity/ICRC-1#47]
https://forum.dfinity.org/t/icrc-1-account-human-readable-format/14682

**Comment by levifeldman** [comment]
The textual formats of the account that are with a checksum of the whole account checksum(principal+subaccount) is better than any format that doesn't because it is 100% error-resistant which is one of the goals of the format. 
Between the two candidates bip-0173 and principal(owner+subaccount) , the principal(owner+subaccount) format grants us the benefit that the main/default account of an owner is the owners principal and I think the value in this is great.

**Comment by levifeldman** [comment]
The textual formats of the account that are with a checksum of the whole account checksum(principal+subaccount) are better than any format that doesn't because it is 100% error-resistant which is one of the goals of the format.
Between the two candidates bip-0173 and principal(owner+subaccount) , the principal(owner+subaccount) format grants us the benefit that the main/default account of an owner is the owners principal.
