### ISSUE TITLE
Transaction deduplication when `created_at_time` is not set

### ISSUE THREAD

**Issue by Maximkaaa** [dfinity/ICRC-1#50]
If `created_at_time` field is not set on transaction, it does not make sense to deduplicate the transaction request. The user may want to send regular transfer once a month and without memo and `created_at_time` such requests would be structurally identical.

I suppose that the standard authors had the same opinion, but the current wording of the standard suggests that if `created_at_time` is not set, the transfer request should be deduplicated by all other fields.

> If the ledger observed a structurally equal transfer payload (i.e., all the transfer argument fields and the caller have the same values) at transaction with index i, it should return variant { Duplicate = record { duplicate_of = i } }.

In any case, this point needs some clarification.

**Comment by roman-kashitsyn** [comment]
>  The user may want to send regular transfer once a month and without memo and created_at_time such requests would be structurally identical.

I'm not 100% sure about that.
The ICP ledger (and the Rust ICRC-1 implementation at DFINITY) uses a deduplication window of 24 hours, so payments once a month won't be deduplicated. We could say that deduplication applies only to transactions that have `created_at_time` set to allow users to opt-out of deduplication. Most clients that rely on deduplication (DFX, Rosetta API) always set `created_at_time`. Disabling deduplication for missing `created_at_time` can also save some space on the ledger and make it easier to write canister code because canisters never need to care about deduplication.

@bogwar, WDTY?

**Comment by roman-kashitsyn** [comment]
I had a conversation with @bogwar, and we agreed that it would make much more sense to disable deduplication for requests that do not specify `created_at_time`. I'll update the spec and the reference implementation.
