### ISSUE TITLE
missing `thumbnail` field and method for canister metadata

### ISSUE THREAD

**Issue by ozwaldorf** [dfinity/ICRC-1#64]
We currently do not have a defined way to store the thumbnail or a url reference to the thumbnail in ICRC-1. Might be beneficial to include `icrc1:thumbnail` as a reserved key for the metadata. In addition, like the other metadata, we should probably also include a `icrc1_thumbnail` method

**Comment by roman-kashitsyn** [comment]
Unfortunately, demanding new `icrc1_*` methods is undesirable because it breaks backward compatibility: an existing compliant implementation suddenly stops being compliant.

Adding new metadata keys should be fine, as long as they use the `icrc1:` prefix: such an extension does not invalidate any compliant code.
